---
name: Test
on:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Run unit tests
        run: go test ./...
